default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dhiotemplate
  password: Hauntmex3
  host: localhost

development:
  <<: *default
  database: crm_template_development

test:
  <<: *default
  database: crm_template_test

production:
  <<: *default
  database: crm_template_production
